[project]
name = "fairgraph"
version = "0.8.3"
description = "Python API for the Human Brain Project Knowledge Graph"
readme = "README.md"
authors = [
    { name="Andrew P. Davison", email="andrew.davison@cnrs.fr" }
]
requires-python = ">=3.7"
license = {text = "Apache Software License"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3"
]
keywords = ["ebrains", "hbp", "metadata", "electrophysiology", "knowledge-graph"]
dependencies=[
    #"openid_http_client @ git+https://github.com/HumanBrainProject/openid_http_client.git#subdirectory=openid_http_client",
    #"pyxus @ git+https://github.com/apdavison/pyxus.git@pystache-jinja2#egg=pyxus&subdirectory=pyxus",
    "ebrains-kg-core",
    "pathlib2",
    "python-dateutil",
    "six",
    "tabulate",
    "requests",
    "tqdm",
    "pyld==0.8.2"
]

[project.urls]
"Homepage" = "https://github.com/HumanBrainProject/fairgraph"

[tool.setuptools.packages.find]
include = ["fairgraph*"]

[build-system]
 requires = [
     "setuptools",
     "wheel",
 ]
 build-backend = "setuptools.build_meta"